# service 1
service:
  # first service
  - name: example-service
    port: 2030
    host: example.com
    email: user-mail@mail.com
    production: true
    path: /
    domains: 
      - example.com
      - www.example.com
  # ----
  - name: example-service-2
    port: 9887
    host: secondary-example.com
    email: user-mail23@mail.com
    production: false
    path: /
    domains: 
      - secondary-example.com
      - www.secondary-example.com
      - www.sub.secondary-example.com