# service 1
service:
  # first service
  - name: example-service
    port: 2030
    host: example.com
    email: user-mail@mail.com
    staging: true
    domains: 
      - example.com
      - www.example.com
  # ----
  - name: example-service-2
    port: 9887
    host: secundary-example.com
    email: user-mail23@mail.com
    staging: false
    domains: 
      - secundary-example.com
      - www.secundary-example.com
      - www.sub.secundary-example.com